"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os  # used for environment variables and docker check

# build paths inside the project (BASE_DIR points to the root folder of the project)
BASE_DIR = Path(__file__).resolve().parent.parent


# development settings

# secret key for django – keep this secret in production
SECRET_KEY = 'django-insecure-u^q^53mr1i4+(1oca4q2-4)8#61t@k!z@jriwwoq3qbtp!29te'

# debug mode – should be False in production
DEBUG = True

# list of allowed hostnames/domain names for the app
ALLOWED_HOSTS = []


# application definition

# list of installed apps: includes django defaults, third-party apps, and our own apps
INSTALLED_APPS = [
    # django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party apps
    'rest_framework',            # django rest framework for api building
    'rest_framework_simplejwt',  # jwt authentication for securing apis
    'drf_spectacular',           # api documentation generator (openapi/swagger)

    # custom apps
    'users',                     # handles user registration, login, and profiles
    'paragraphs',                # manages paragraph storage and search features
]

# middleware: processes requests and responses
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',           # security headers and features
    'django.contrib.sessions.middleware.SessionMiddleware',    # session management
    'django.middleware.common.CommonMiddleware',               # common request/response handling
    'django.middleware.csrf.CsrfViewMiddleware',                # csrf protection for forms
    'django.contrib.auth.middleware.AuthenticationMiddleware', # associates users with requests
    'django.contrib.messages.middleware.MessageMiddleware',    # messaging framework
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # prevents clickjacking attacks
]

# root urls module
ROOT_URLCONF = 'backend.urls'

# template engine configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # template engine
        'DIRS': [],               # extra template directories (none for now)
        'APP_DIRS': True,         # look for templates in each app's templates folder
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',      # adds debug info to templates
                'django.template.context_processors.request',    # adds request object to templates
                'django.contrib.auth.context_processors.auth',   # adds user/auth info to templates
                'django.contrib.messages.context_processors.messages', # adds messages to templates
            ],
        },
    },
]

# wsgi entry point – used by servers to run the app
WSGI_APPLICATION = 'backend.wsgi.application'


# database
# check if the app is running inside docker
IN_DOCKER = os.path.exists('/.dockerenv')  # used to switch host/port for docker

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',               # database backend
        'NAME': os.getenv('DB_NAME', 'codemonk'),            # db name (env or default)
        'USER': os.getenv('DB_USER', 'codemonk_user'),       # db username
        'PASSWORD': os.getenv('DB_PASSWORD', 'anil209'),     # db password
        'HOST': 'db' if IN_DOCKER else '127.0.0.1',           # db host (docker vs local)
        'PORT': '3306' if IN_DOCKER else '3307',              # db port (docker vs local)
    }
}


# password validation rules
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # no passwords too similar to user info
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',            # enforce minimum length
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',           # block common passwords
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',          # block all-numeric passwords
    },
]

# celery configuration – used for background task processing
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/0')       # broker (task queue)
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://redis:6379/0')  # backend (stores results)

# rest framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # use jwt auth
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',      # auto-generate schema for swagger docs
}

# spectacular (swagger/openapi) documentation settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Backend API Project',                      # api doc title
    'DESCRIPTION': 'API documentation for Codemonk Backend Project',  # api doc description
    'VERSION': '1.0.0',                                  # version number
    'SERVE_INCLUDE_SCHEMA': False,                       # don't include schema in served docs
}


# internationalization
LANGUAGE_CODE = 'en-us'   # language setting
TIME_ZONE = 'UTC'         # time zone setting
USE_I18N = True           # enable django's internationalization system
USE_TZ = True             # enable timezone-aware datetimes


# static files (css, js, images)
STATIC_URL = 'static/'    # url path for serving static files

# default primary key type for models
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "debug-task-every-minute": {
        "task": "paragraphs.tasks.debug_task",
        "schedule": crontab(minute="*/1"),  # every 1 minute
    },
}
